repos:
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        language_version: python3.9
  - repo: local
    hooks:
      - id: tests
        name: run unit tests
        entry: python -m unittest discover
        language: python
        language_version: python3.9
        pass_filenames: false
